version: "3.8"

services:
  api:
    container_name: solarihub-api
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production

  web:
    container_name: solarihub-web
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production 