FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY tsconfig.base.json ./
COPY nx.json ./
COPY api ./api
COPY libs ./libs
COPY types ./types

RUN npm install
RUN npx nx build api

CMD ["node", "dist/api/main.js"] 