FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY tsconfig.base.json ./
COPY nx.json ./
COPY apps/frontend ./apps/frontend
COPY libs ./libs

RUN npm install
RUN npx nx build frontend

EXPOSE 3000

CMD ["npx", "vite", "preview", "--host", "--port", "3000"] 