version: "3.8"

services:
  backend:
    container_name: solarihub-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production

  frontend:
    container_name: solarihub-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production 