version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile.backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
    volumes:
      # Mount source for development (optional)
      - ./apps/backend/src:/app/src
    networks:
      - solarihub

  frontend:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:4000
    depends_on:
      - backend
    networks:
      - solarihub

networks:
  solarihub:
    driver: bridge

volumes:
  node_modules: 