FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY tsconfig.base.json ./
COPY nx.json ./
COPY apps/backend ./apps/backend
COPY libs ./libs

RUN npm install
RUN npx nx build backend

CMD ["node", "dist/backend/main.js"] 