services:
  # Backend API Service (Docker)
  - type: web
    name: solarihub-backend
    runtime: docker
    dockerfilePath: ./deployment/docker/Dockerfile.backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: FRONTEND_URL
        value: https://solarihub-frontend.vercel.app
    autoDeploy: true 