services:
  # SolariHub Backend API Service (Docker with Runtime Dependencies)
  - type: web
    name: solarihub-backend
    runtime: docker
    dockerfilePath: ./Dockerfile.simple
    plan: starter
    region: oregon
    buildFilter:
      paths:
        - apps/backend/**
        - libs/**
        - tools/**
        - package*.json
        - nx.json
        - tsconfig*.json
        - Dockerfile.simple
    healthCheckPath: /api/health/ping
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "15m"
      - key: JWT_REFRESH_EXPIRES_IN
        value: "7d"
      - key: BCRYPT_ROUNDS
        value: "12"
      - key: RATE_LIMIT_WINDOW_MS
        value: "900000"
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "100"
      - key: CORS_ORIGIN
        value: "*"
      - key: LOG_LEVEL
        value: "info"
      - key: MAX_REQUEST_SIZE
        value: "10mb"
      - key: POSTGRES_HOST
        sync: false
      - key: POSTGRES_PORT
        value: "5432"
      - key: POSTGRES_DB
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_PASSWORD
        sync: false

  # SolariHub Frontend Application (Docker)
  - type: web
    name: solarihub-frontend-app
    runtime: docker
    dockerfilePath: ./deployment/docker/Dockerfile.frontend
    plan: starter
    region: frankfurt
    buildFilter:
      paths:
        - apps/frontend/**
        - libs/**
        - deployment/**
        - package*.json
        - nx.json
        - tsconfig.base.json
    domains:
      - app.solarihub.net
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: VITE_API_URL
        value: https://api.app.solarihub.net
      - key: VITE_APP_URL
        value: https://app.solarihub.net
      - key: VITE_ENODE_CLIENT_ID
        sync: false
      - key: VITE_RECAPTCHA_SITE_KEY
        sync: false
      - key: VITE_SENTRY_DSN
        sync: false
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: solarihub-postgres
    databaseName: solarihub
    user: solarihub_user
    plan: starter

  - name: solarihub-redis
    plan: starter 