services:
  - type: web
    name: solarihub-backend
    runtime: node
    buildCommand: npx nx build backend
    startCommand: node dist/backend/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
    autoDeploy: true 